version: 2
updates:
  # Majo.exe Dashboard
 - package-ecosystem: "npm"
   directory: "/packages/dashboard"
   schedule:
    interval: "daily"
   labels:
    - "dependencies"
    - "dashboard"
  # Majo.exe Bot
 - package-ecosystem: "npm"
   directory: "/packages/majoexe"
   schedule:
    interval: "daily"
   labels:
    - "dependencies"
    - "bot"