name: Prettier check

on:
 push:
  branches: [master]
 pull_request:
  branches: [master]

jobs:
 format:
  name: ✨ Prettier
  runs-on: ubuntu-latest
  strategy:
   matrix:
    node-version: [16.x]
  steps:
   - uses: actions/checkout@v1
   - run: node -v
   - run: npm i prettier -f
   - run: npm run format:check
